const API_BASE = '/api/v1'

export const endpoints = {
  auth: {
    login: `${API_BASE}/auth/login`,
    logout: `${API_BASE}/auth/logout`,
    refresh: `${API_BASE}/auth/refresh`,
    me: `${API_BASE}/auth/me`,
    profile: `${API_BASE}/auth/profile`,
  },
  dashboard: {
    index: `${API_BASE}/dashboard`,
  },
  teachers: {
    list: `${API_BASE}/teachers`,
    detail: (id: string | number) => `${API_BASE}/teachers/${id}`,
    create: `${API_BASE}/teachers`,
    update: (id: string | number) => `${API_BASE}/teachers/${id}`,
    delete: (id: string | number) => `${API_BASE}/teachers/${id}`,
    bulkDelete: `${API_BASE}/teachers/bulk-delete`,
    export: `${API_BASE}/teachers/export`,
    import: `${API_BASE}/teachers/import`,
  },
  agendas: {
    list: `${API_BASE}/agendas`,
    detail: (id: string | number) => `${API_BASE}/agendas/${id}`,
    create: `${API_BASE}/agendas`,
    update: (id: string | number) => `${API_BASE}/agendas/${id}`,
    delete: (id: string | number) => `${API_BASE}/agendas/${id}`,
    bulkDelete: `${API_BASE}/agendas/bulk-delete`,
  },
  galleries: {
    list: `${API_BASE}/galleries`,
    detail: (id: string | number) => `${API_BASE}/galleries/${id}`,
    create: `${API_BASE}/galleries`,
    update: (id: string | number) => `${API_BASE}/galleries/${id}`,
    delete: (id: string | number) => `${API_BASE}/galleries/${id}`,
    bulkDelete: `${API_BASE}/galleries/bulk-delete`,
  },
  testimonials: {
    list: `${API_BASE}/testimonials`,
    detail: (id: string | number) => `${API_BASE}/testimonials/${id}`,
    create: `${API_BASE}/testimonials`,
    update: (id: string | number) => `${API_BASE}/testimonials/${id}`,
    delete: (id: string | number) => `${API_BASE}/testimonials/${id}`,
    bulkDelete: `${API_BASE}/testimonials/bulk-delete`,
  },
  activities: {
    list: `${API_BASE}/activities`,
    detail: (id: string | number) => `${API_BASE}/activities/${id}`,
    create: `${API_BASE}/activities`,
    update: (id: string | number) => `${API_BASE}/activities/${id}`,
    delete: (id: string | number) => `${API_BASE}/activities/${id}`,
    bulkDelete: `${API_BASE}/activities/bulk-delete`,
  },
  facilities: {
    list: `${API_BASE}/facilities`,
    detail: (id: string | number) => `${API_BASE}/facilities/${id}`,
    create: `${API_BASE}/facilities`,
    update: (id: string | number) => `${API_BASE}/facilities/${id}`,
    delete: (id: string | number) => `${API_BASE}/facilities/${id}`,
    bulkDelete: `${API_BASE}/facilities/bulk-delete`,
  },
  achievements: {
    list: `${API_BASE}/achievements`,
    detail: (id: string | number) => `${API_BASE}/achievements/${id}`,
    create: `${API_BASE}/achievements`,
    update: (id: string | number) => `${API_BASE}/achievements/${id}`,
    delete: (id: string | number) => `${API_BASE}/achievements/${id}`,
    bulkDelete: `${API_BASE}/achievements/bulk-delete`,
  },
  news: {
    list: `${API_BASE}/news`,
    detail: (id: string | number) => `${API_BASE}/news/${id}`,
    create: `${API_BASE}/news`,
    update: (id: string | number) => `${API_BASE}/news/${id}`,
    delete: (id: string | number) => `${API_BASE}/news/${id}`,
    bulkDelete: `${API_BASE}/news/bulk-delete`,
  },
  users: {
    list: `${API_BASE}/users`,
    detail: (id: string | number) => `${API_BASE}/users/${id}`,
    create: `${API_BASE}/users`,
    update: (id: string | number) => `${API_BASE}/users/${id}`,
    delete: (id: string | number) => `${API_BASE}/users/${id}`,
    bulkDelete: `${API_BASE}/users/bulk-delete`,
  },
  roles: {
    list: `${API_BASE}/roles`,
    detail: (id: string | number) => `${API_BASE}/roles/${id}`,
    create: `${API_BASE}/roles`,
    update: (id: string | number) => `${API_BASE}/roles/${id}`,
    delete: (id: string | number) => `${API_BASE}/roles/${id}`,
  },
  permissions: {
    list: `${API_BASE}/permissions`,
  },
  media: {
    list: `${API_BASE}/media`,
    upload: `${API_BASE}/media`,
    delete: (id: string | number) => `${API_BASE}/media/${id}`,
    bulkDelete: `${API_BASE}/media/bulk-delete`,
  },
  content: {
    hero: `${API_BASE}/content/hero`,
    heroUpdate: (id: string | number) => `${API_BASE}/content/hero/${id}`,
    heroDelete: (id: string | number) => `${API_BASE}/content/hero/${id}`,
    about: `${API_BASE}/content/about`,
    visionMission: `${API_BASE}/content/vision-mission`,
    visionMissionUpdate: (id: string | number) => `${API_BASE}/content/vision-mission/${id}`,
    principal: `${API_BASE}/content/principal`,
    contactInfo: `${API_BASE}/content/contact-info`,
    contactInfoUpdate: (id: string | number) => `${API_BASE}/content/contact-info/${id}`,
    contactInfoDelete: (id: string | number) => `${API_BASE}/content/contact-info/${id}`,
    socialMedia: `${API_BASE}/content/social-media`,
    socialMediaUpdate: (id: string | number) => `${API_BASE}/content/social-media/${id}`,
    socialMediaDelete: (id: string | number) => `${API_BASE}/content/social-media/${id}`,
    navigation: `${API_BASE}/content/navigation`,
    navigationUpdate: (id: string | number) => `${API_BASE}/content/navigation/${id}`,
    navigationDelete: (id: string | number) => `${API_BASE}/content/navigation/${id}`,
    footer: `${API_BASE}/content/footer`,
  },
  settings: {
    list: `${API_BASE}/settings`,
    upsert: `${API_BASE}/settings`,
    update: (id: string | number) => `${API_BASE}/settings/${id}`,
  },
  seo: {
    list: `${API_BASE}/seo`,
    detail: (pageKey: string) => `${API_BASE}/seo/${pageKey}`,
    create: `${API_BASE}/seo`,
    update: (pageKey: string) => `${API_BASE}/seo/${pageKey}`,
    delete: (id: string | number) => `${API_BASE}/seo/${id}`,
  },
  contacts: {
    list: `${API_BASE}/contacts`,
    detail: (id: string | number) => `${API_BASE}/contacts/${id}`,
    markRead: (id: string | number) => `${API_BASE}/contacts/${id}/read`,
    delete: (id: string | number) => `${API_BASE}/contacts/${id}`,
  },
  public: {
    landing: `${API_BASE}/public/landing`,
    contact: `${API_BASE}/public/contact`,
    visionMission: `${API_BASE}/public/vision-mission`,
    news: `${API_BASE}/public/news`,
    newsDetail: (slug: string) => `${API_BASE}/public/news/${slug}`,
    agendas: `${API_BASE}/public/agendas`,
    agendaDetail: (slug: string) => `${API_BASE}/public/agendas/${slug}`,
    teachers: `${API_BASE}/public/teachers`,
    teacherDetail: (slug: string) => `${API_BASE}/public/teachers/${slug}`,
    activities: `${API_BASE}/public/activities`,
    activityDetail: (slug: string) => `${API_BASE}/public/activities/${slug}`,
    galleries: `${API_BASE}/public/galleries`,
    galleryDetail: (slug: string) => `${API_BASE}/public/galleries/${slug}`,
    testimonials: `${API_BASE}/public/testimonials`,
    facilities: `${API_BASE}/public/facilities`,
    facilityDetail: (slug: string) => `${API_BASE}/public/facilities/${slug}`,
    achievements: `${API_BASE}/public/achievements`,
    achievementDetail: (slug: string) => `${API_BASE}/public/achievements/${slug}`,
  },
} as const
